version: "3"
services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    restart: always
  frontend:
    build: "./frontend"
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: always
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
  redis:
    image: redis
    restart: always
